### PR TITLE
a recipe for the ALPACA.

### PR DESCRIPTION
**Pull request by tugberk92**

### CODE REVIEW

**Comment by olantwin** [comment]
Since we don't (yet) use ALPACA in FairShip, I think we should not change `generators.sh` yet. There is no harm in merging the recipe though, if nothing depends on it by default.

I would like to avoid to repeat what we did with MadGraph...

**Comment by ThomasRuf** [comment]
what would be the problem? Since we have our own copy of alpaca, we are in full control. If it works once, will continue to work.

**Comment by ThomasRuf** [comment]
does anybody know why python3 is now required? I thought the build was setup for python2.7 and should be python3 compatible.

==> Building Python@v3.6.8
==> Python is being built (use --debug for full output): failed    
ERROR: Error while executing /media/truf/disk1/SHiPTest/sw/SPECS/ubuntu1804_x86-64/Python/v3.6.8-1/build.sh on `ubuntu'.

**Comment by olantwin** [comment]
#34 changes the default python version built. We can override it in `defaults_fairship.sh`.

**Comment by olantwin** [comment]
While most recipes can be compatible with both, we need to decide which version to use at build time. Maybe we should make two sets of defaults: `defaults_fairship_python{2,3}.sh` and simlink `defaults_fairship.sh` to python2 for now and change to python3 when ready?

**Comment by ThomasRuf** [comment]
I tried your recipe. It did compiled alpaca
==> Building alpaca@v1.1
==> alpaca is being built (use --debug for full output): ok 
Using cached build for alpaca
...

however, when setting the environment, nothing is know about alpaca. Moreover, it also does not appear in the list of currently loaded Modulefiles. However it exists:
ls sw/SOURCES/alpaca/v1.1/master
ls sw/MODULES/ubuntu1804_x86-64/alpaca/v1.1-1

it also exists 
sw/ubuntu1804_x86-64/alpaca/v1.1-1/etc/profile.d/init.sh
which when executed defines the env variables, for example ALPACA_ROOT. However, what is missing is $ALPACA_ROOT/bin or equivalent. 

so, something is not yet quite correct.

**Comment by tugberk92** [comment]
I did the following treatment from pythia.sh;
```https://github.com/ShipSoft/shipdist/pull/37/commits/94e7718d95afb008d587f73e5a0b144b8725d3f0```

Then, built the alpaca to the local PC _(Operating System is **MACOSX10.15.1**)_. 

The result is

>> alibuild/aliBuild -c shipdist/ --defaults fairship build alpaca

```
==> Packages will be built in the following order:
     - alpaca@master
Using cached build for defaults-release
Using cached build for alpaca

==> Build of alpaca successfully completed on `MBP'.
    Your software installation is at:
    
      /Users/atakan/Documents/GitHub/ShipSoft/sw/osx_x86-64
    
    You can use this package by loading the environment:
    
      alienv enter alpaca/latest-fairship
```

>> alibuild/alienv enter --shellrc alpaca/latest-fairship

    
```
WARNING: System Integrity Protection is enabled. You might run into environment problems if you do not disable it.
WARNING: not updating modulefiles
alpaca/latest-fairship(8):ERROR:102: Tcl command execution failed: setenv ALPACA_ROOT $::env(BASEDIR)/alpaca/$version

No Modulefiles Currently Loaded.
```

**Comment by tugberk92** [comment]
Same error (https://github.com/ShipSoft/shipdist/pull/37#issuecomment-562219101) occurred at lxplus as well.

**Comment by ThomasRuf** [comment]
I tried the last commit on my local machine. It build alpaca:
==> Building alpaca@v1.1
==> alpaca is being built (use --debug for full output): ok 
Using cached build for alpaca
Using cached build for protobuf
...
however when setting up the environment, nothing about alpaca, not under currently loaded Modulefiles, nor any env variable is set.

**Pull request merged**
