### PR TITLE
Added Conditions Database dependencies.

### PR DESCRIPTION
**Pull request by tvrancken**
This PR adds all required dependencies to the FairSHiP aliBuild recipe. It should be merged along with https://github.com/ShipSoft/FairShip/pull/346.

### CODE REVIEW

**Comment by olantwin** [comment]
Could you please also check for these modules in the `prefer_system_check` in line 13?

Without this, it could be that aliBuild falsely reports that the packages on the system are sufficient and doesn't install your needed dependencies.

**Comment by tvrancken** [comment]
I will add them there.

**Comment by tvrancken** [comment]
It's done.

**Comment by olantwin** [comment]
Thanks a lot!

Looks good to me for merging.

**Comment by ThomasRuf** [comment]
Why do we suddenly require alibuild to be installed via pip? The default procedure is to do it via git clone. This has the advantage that it is under our control what version we use.

**Comment by olantwin** [comment]
> Why do we suddenly require alibuild to be installed via pip? The default procedure is to do it via git clone. This has the advantage that it is under our control what version we use.

You're right, it makes no sense. If aliBuild is installed, there's no point in installing it again (and could actually cause problems, as python2 aliBuild and python3 aliBuild use different hashing algorithms), and if it's not installed, aliBuild isn't available to install aliBuild...

As this is unrelated to the conditions DB it's probably better to fix it separately. I'll create a separate pull request to correct this.

**Comment by tvrancken** [comment]
> 
> 
> > Why do we suddenly require alibuild to be installed via pip? The default procedure is to do it via git clone. This has the advantage that it is under our control what version we use.
> 
> You're right, it makes no sense. If aliBuild is installed, there's no point in installing it again (and could actually cause problems, as python2 aliBuild and python3 aliBuild use different hashing algorithms), and if it's not installed, aliBuild isn't available to install aliBuild...
> 
> As this is unrelated to the conditions DB it's probably better to fix it separately. I'll create a separate pull request to correct this.

I was also wondering about that. The alibuild install instruction via PIP was already in this recipe. We did not add it. Re-installing like this could cause a version change I guess. But since this is a recipe for aliBuild, it does seem weird to install aliBuild via its own build recipe.

If you want me to change anything, please let me know.

**Comment by olantwin** [comment]
@ThomasRuf  Could we merge this?

There is no point in fixing the aliBuild installation with pip before it's merged, as it's a one-line fix which will create a conflict with this change-set.

**Pull request merged**
