### PR TITLE
Work on Python3 copatibilities

### PR DESCRIPTION
**Pull request by siscia**

### CODE REVIEW

**Comment by ThomasRuf** [comment]
I completely overlooked that shipdist is now setup for python3 only. This breaks any build of fairship-2018 and muflux branch.  In addition, I cannot build python3 on ubuntu because of 

import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

We need an urgent solution.

**Comment by olantwin** [comment]
A sketch of a possible solution: Use `$PYTHON_VERSION` to determine which python version is used (NB: would only work for for python built by aliBuild if I'm not mistaken, but this could be generalised) and use this to add two cases to the recipes affected:

- [ ] `fairship.sh`
- [ ] `boost.sh`
- [ ] `python-modules.sh`
- [ ] `root.sh`

The `python.sh` recipe would also need minor adjustments.

With those changes, we only need to override the python version in `defaults-fairship.sh`.

**Comment by ThomasRuf** [comment]
are you sure? There are many harcdcoded ...python3.6m

**Comment by olantwin** [comment]
That's why we need to modify the recipes I list to not hardcode the version anymore.

**Comment by olantwin** [comment]
As a very urgent solution you could locally roll-back this commit:

`git revert -n 43657c9889c5a22f4dce16ac0f4e479d526a3752`

**Comment by ThomasRuf** [comment]
ok, understand. other possibility, I am trying right now, use a different branch based on 69e2a897bc2988cefc29a9d180f939b8e59a2386 and importing xerces.sh and new alpaca and generators.

**Comment by ThomasRuf** [comment]
you had the same idea!

**Comment by olantwin** [comment]
So you for now have a workaround?

I will try to implement my outlined solution, but I can't make any promises as to how long this takes.
If anyone could help, that would of course be appreciated!

**Pull request merged**
