### PR TITLE
Add support of python for Pythia

### PR DESCRIPTION
**Pull request by shir994**
Provide flag to build Pythia with python support. If python is not found, should not fail, but build without it.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
May I ask why this is needed? We already have full access to Pythia via ROOT dictionaries. Could you show an example which does not work currently?

**Comment by shir994** [comment]
I want to save events in LHE files, calling pythia from python. Usually, I use ``` newLHA = LHAupFromPYTHIA8(pythia.process, pythia.info)```. I did not find LHAupFromPYTHIA8 in the ROOT-Pythia.

**Comment by ThomasRuf** [comment]
ROOT.gROOT.ProcessLine('#include "Pythia8/LesHouches.h"')
pythia = P8gen.getPythiaInstance()
LHA = ROOT.LHAupFromPYTHIA8(pythia.process, pythia.info)

<ROOT.Pythia8::LHAupFromPYTHIA8 object at 0x561bb3a3f2b0>

I am worried about this pythonwrapper, that it does not match with the running pythia8 instance. Sometimes, we also have more than one pythia instance.

**Comment by ThomasRuf** [comment]
if you have
tp = ROOT.TPythia8() then this should work
pythia = tp.Pythia8()

and then the above commands

**Comment by shir994** [comment]
I use it to deal with new generator, we are preparing for DarkMatter scattering.
This bit needed only to hadronize and save events to LHE file, no particular generator is needed here.

I do use FairShip env, ```alienv enter ...```.

No, as you can see above, I already used what you suggested to do, 

> if you have
tp = ROOT.TPythia8() then this should work
pythia = tp.Pythia8()
and then the above commands

and indeed that works for pythia, but it does not solve the problem of ```LHA = ROOT.LHAupFromPYTHIA8(pythia.process, pythia.info)```

**Comment by ThomasRuf** [comment]
issue with namespace, try:
import ROOT
ROOT.gROOT.ProcessLine('#include "Pythia8/LesHouches.h"')
tp = ROOT.TPythia8()
pythia = tp.Pythia8()
LHA = ROOT.Pythia8.LHAupFromPYTHIA8(pythia.process, pythia.info)
<ROOT.Pythia8::LHAupFromPYTHIA8 object at 0x5654ea9420f0>

**Pull request closed without merging**
