### PR TITLE
Update README to contain information relevant to SHiP

### PR DESCRIPTION
**Pull request by olantwin**
The current README contains no information relevant to SHiP.

I thought it might be useful to list information regarding dependencies, different tested platforms etc. here (and maybe some could be moved here from the FairShip README).

For now I add info on platforms I have recently worked with (Fedora 30/31), but will add information as I encounter it. Feel free to suggest additions/changes. In particular, I have no (recent) experiences with FairShip on Ubuntu, so would appreciate help there.

### CODE REVIEW

**Comment by olantwin** [comment]
@antonioiuliano2, @shir944, would appreciate your comment, in case you're not watching the repository.

**Comment by shir994** [comment]
I have been building it back in November on Ubuntu 16.04 and might rebuild it soon on Ubuntu 18.04. So far there was no problems in 16.04, except those you have fixed:
```
-import tkinter(instead of _tkinter)
-xerces bug
-apt-get install tcl8.6 tk8.6 tcl8.6-dev tk8.6-dev tcl8.6-doc tk8.6-doc,
apt-get install python3-tk
```

then just run:
`aliBuild -c shipdist --default fairship --no-local ROOT build FairShip`

**Comment by ThomasRuf** [comment]
Always worked with Ubuntu. Whenever a package was missing, used -apt-get install. Will soon move to the new Ubuntu version, 20.04.

**Comment by antonioiuliano2** [comment]
You should find the list ok packages to be installed on Ubuntu from FAIRSHIP/system/install_on_ubuntu.sh. It should be updated too, when we move to the 20.04 version

**Comment by olantwin** [comment]
Thanks for bringing that script to my attention! I forgot it existed!

**Pull request merged**
