### PR TITLE
Backport changes from SND@LHC

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by olantwin** [comment]
A second pull request will manually backport a few changes from `sndsw.sh` to `fairship.sh`.

We can also consider removing a few things not needed for FairShip.

**Comment by ThomasRuf** [comment]
should we first make a tag for the present version?

**Comment by olantwin** [comment]
Tagging the present version is a good idea (but can even be done later: one can tag any commit at any time).

**Comment by ThomasRuf** [comment]
yes, from snddist/defaults-release.sh and sndsw.sh. Are you working on this?

**Comment by olantwin** [comment]
> yes, from snddist/defaults-release.sh and sndsw.sh. Are you working on this?

Not quite sure what you are replying to.

If you mean on back-parting changes form `sndsw.sh` to `fairship.sh`, I can maybe look into it.

I would propose we just use `defaults-release.sh` for now, like we do in SND@LHC, unless there's a good reason not to.

**Comment by ThomasRuf** [comment]
I was referring to "A second pull request will manually backport a few changes from sndsw.sh to fairship.sh."

**Pull request merged**
