### PR TITLE
Migrate to LHAPDF6

### PR DESCRIPTION
**Pull request by olantwin**
Modifications to `shipdist` required for `lhapdf6` so that we can finally move on from the unmaintained `lhapdf5`.

Still requires some testing, and currently the python module does not seem to be installed correctly (it's not used by FairShip AFAIK, but would still be nice to fix this, as it is needed for the helper to download PDF-sets).

### CODE REVIEW

**Comment by olantwin** [comment]
If anyone would like to test, I built a docker image with this modified `shipdist` and FairShip `master`: `olantwin/fairship:200225-lhapdf6`.

**Comment by olantwin** [comment]
@ThomasRuf This should be in a state that you can try it, to see whether lhapdf6 works as expected.

**Comment by ThomasRuf** [comment]
it builds without errors, but when trying to setup the environment, it fails. The module file is at 
sw/MODULES/ubuntu2004_x86-64/lhapdf/v6.2.3_FAIRSHIP-1 but it looks for  'lhapdf/v6.2.3_FAIRSHIP-'

maybe i did something wrong when implementing the changes, will check tomorrow.


alibuild/alienv enter FairShip/latest-master-fairship
Loading Tauolapp/v1.1.5-ship-2
  ERROR: Unable to locate a modulefile for 'lhapdf/v6.2.3_FAIRSHIP-'
  ERROR: Requirement 'lhapdf/v6.2.3_FAIRSHIP-' is not loaded

Loading PHOTOSPP/v3.61-2
  ERROR: Requirement 'Tauolapp/v1.1.5-ship-2' is not loaded

Loading EvtGen/R01-06-00-ship-2
  ERROR: Requirement 'Tauolapp/v1.1.5-ship-2' is not loaded

Loading GEANT3/v2-7-2
  Module ERROR: can't read "::env(GEANT3_ROOT)": no such variable
    In '/media/disk0/SHiPBuild/sw/MODULES/ubuntu2004_x86-64/GEANT3/v2-7-2'
    Please contact <root@localhost>

Loading vgm/4.3-alice1_FAIRSHIP-2
  Module ERROR: can't read "::env(VGM_ROOT)": no such variable
    In '/media/disk0/SHiPBuild/sw/MODULES/ubuntu2004_x86-64/vgm/4.3-alice1_FAIRSHIP-2'
    Please contact <root@localhost>

Loading GEANT4_VMC/v5-0-p5-2
  ERROR: Requirement 'vgm/4.3-alice1_FAIRSHIP-2' is not loaded

Loading FairRoot/ship-v18.4.1-2
  ERROR: Requirement 'GEANT3/v2-7-2' is not loaded

Loading alpaca/v1.1-1
  Module ERROR: can't read "::env(ALPACA_ROOT)": no such variable
    In '/media/disk0/SHiPBuild/sw/MODULES/ubuntu2004_x86-64/alpaca/v1.1-1'
    Please contact <root@localhost>

Loading FairShip/latest-master-fairship
  ERROR: Load of requirement 'lhapdf/v6.2.3_FAIRSHIP-' failed
  ERROR: Load of requirement 'Tauolapp/v1.1.5-ship-2' failed
  ERROR: Load of requirement 'vgm/4.3-alice1_FAIRSHIP-2' failed
  ERROR: Load of requirement 'GEANT3/v2-7-2' failed
  ERROR: Requirement 'PHOTOSPP/v3.61-2' is not loaded

**Comment by olantwin** [comment]
Could you check again with the two GENIE and Tauola module file changes I just pushed? I hope that will fix it.

If not, I'll need to dig a bit deeper.

**Comment by ThomasRuf** [comment]
it works now, but I think more changes are required for default-fairship.sh to be used with cvmfs:
lhapdf:
    prefer_system_check: |
      ls $LHAPDF_ROOT/ > /dev/null && \
 ... 
ls $PYTHIA_ROOT/lib/libpythia8lhapdf.so > /dev/null && \

**Comment by olantwin** [comment]
I updated the checks.

I removed the ones for explicit LHAPDF libraries and the python bindings for now, as I wasn't sure whether they'd be the same, but we can tighten the checks again later if needed.

**Comment by ThomasRuf** [comment]
OK. Now I have to see how to merge this with my modifications. I added a tag to shipdist, v3-00, same as for fairship. I will then merge first your changes.

**Comment by olantwin** [comment]
You can most likely rebase your changes ontop of mine using `git rebase`.

**Comment by ThomasRuf** [comment]
My knowledge of git is not enough. I did 
git clone https://github.com/ThomasRuf/shipdist 
git rebase
Aktueller Branch master ist auf dem neuesten Stand

missing something between.

**Comment by ThomasRuf** [comment]
I can confirm that it works. Using, readString("PDF:pSet = LHAPDF6:cteq6l1"):

LHAPDF 6.2.3 loading all 1 PDFs in set cteq6l1
cteq6l1, version 4; 1 PDF members
LHAPDF 6.2.3 loading /media/disk0/SHiPBuild/sw/ubuntu2004_x86-64/lhapdf/v6.2.3_FAIRSHIP-1/share/LHAPDF/cteq6l1/cteq6l1_0000.dat
cteq6l1 PDF set, member #0, version 4; LHAPDF ID = 10042
...
Thanks for using LHAPDF 6.2.3. Please make sure to cite the paper:
  Eur.Phys.J. C75 (2015) 3, 132  (http://arxiv.org/abs/1412.7420)

**Pull request merged**
