### PR TITLE
update dependencies recipes to build out of the box in openstack

### PR DESCRIPTION
**Pull request by siscia**
Hi all,

I was getting familiar with the repository.

The dependencies recipes where a little outdated and it wasn't building from scratch properly.

At the moment this is been tested only on CC7, is possible to test as well on SLC6, for MAC I have more issues with the hardware at the moment.

In the process I also create another docker image (accessible here: https://gitlab.cern.ch/smosciat/shiptest/container_registry) to build FairShip based on alidock.

### CODE REVIEW

**Comment by olantwin** [comment]
Thanks! I can try testing on Fedora (quite a few other changes are necessary there, which I'll try to upstream soon...).

Looking forward to your other contributions :)

**Comment by siscia** [comment]
Also, keep in mind that compiling root requires quite a bit of memory (RAM) that is not provided by the standar open stack machine (if I remember correctly I tried  the medium size ~7GB of RAM).

The easy solution in such cases is to allocate some swap space.

Maybe you were already aware of this "workaround" or maybe I could provide some generic instructions.

:)

**Comment by olantwin** [comment]
I just took the easy way out and used the `ship-dockerbuilder` instance on openstack (m2-2xlarge, so 30GB RAM :D ). I can give you access to that one if you like.

**Comment by ThomasRuf** [comment]
yes, indeed, i always allocate swap space on my local disks.

**Pull request merged**
